---

##### ChangeCofnig  zabbix_agentd.conf
- name: change zabbix_agentd.conf Hostname
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: 'Hostname=Zabbix server'
    line: "Hostname={{ ansible_hostname }}"
  become: yes
    
- name: change zabbix_agentd.conf ServerActive
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: 'ServerActive=127.0.0.1'
    line: "ServerActive={{ zabbix_host }}"
  become: yes

- name: change zabbix_agentd.conf Server
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: 'Server=127.0.0.1'
    line: "Server={{ zabbix_host }}"
  become: yes

- name: change zabbix_agentd.conf EnableRemoteCommands
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: '# EnableRemoteCommands=0'
    line: 'EnableRemoteCommands=1'
  become: yes

- name: change zabbix_agentd.conf LogRemoteCommands
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: '# LogRemoteCommands=0'
    line: 'LogRemoteCommands=1'



##### Enable and Activate zabbix-agent

- name: zabbix systemd
  systemd:
    name: zabbix-agent
    enabled: yes
    state: started
