#Install Zabbix-Agent
#

---
- hosts: all
  become: yes
  remote_user: dcaraus
  vars:
    zabbix_host: 51.250.6.29
    centos7_rpm: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    ubuntu20_04_deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
    ubuntu20_04_file: zabbix-release_5.0-1+focal_all.deb 
  roles:
    - zabbix.agent
